services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: FHSSweb1!
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - dev_network

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: FHSSweb1!
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console
    networks:
      - dev_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    platform: linux/amd64 # This is required for M4 Macs
    container_name: keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: FHSSweb1!
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: FHSSweb1!
      KC_HOSTNAME: localhost
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - dev_network

volumes:
  postgres_data:
  minio_data:

networks:
  dev_network:
    driver: bridge
